name: cargo-geiger
on:
  pull_request:
    paths:
      - "sources/**"
      - ".github/workflows/geiger.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  geiger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: files
        uses: Ana06/get-changed-files@v2.2.0
        with:
          format: json
      - name: Cache rust stuff
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-geiger-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-geiger-
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Install cargo-geiger
        run: cargo install cargo-geiger
      - name: Run cargo-geiger on changed sources
        run: |
          shopt -s globstar
          readarray -t TEMP <<< "$(jq -r '.[]' <<<'${{ steps.files.outputs.added_modified }}')"

          FAIL=0
          while IFS= read -r -d $'\0' i; do
            if [[ "$i" == *"sources"* ]]; then
              SRC_DIR=$(echo "$i" | cut -d'/' -f-2)
              if [ -d "$SRC_DIR" ] && [ -f "$SRC_DIR/Cargo.toml" ]; then
                echo "::group::cargo-geiger $SRC_DIR"
                (cd "$SRC_DIR" && cargo geiger --output-format HannuHietalahti) || FAIL=1
                echo "::endgroup::"
              fi
            fi
          done < <(printf "%s\n" "${TEMP[@]}" | cut -d'/' -f-2 | sort -u | grep '^sources' | tr '\n' '\0')

          exit $FAIL
